---
all:
  children:
    target_hosts:
      hosts:
        192.168.137.1: #replace with actual target host IP
        192.168.137.2: #replace with actual target host IP
      vars:
        user_name: vinod #replace with real user name
        user_desc: "User decription goes here"
      

